import os
from pprint import pprint

from firefly.application.container import Container

os.environ['ENV'] = 'dev'
os.environ['CONTEXT'] = 'distributed_events'
os.environ['REGION'] = 'us-west-2'
os.environ['USER_POOL_ID'] = 'us-west-2_R09Wws89p'
container = Container()
container.kernel.boot()

token = 'eyJraWQiOiJmYk5OT2hqY2V4TGoyVko0WWhQWVM1UDliTmpsdFwvZDA4NVNMTkY3cVF3WT0iLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiJiMmE0MWZlNy03MzNlLTRjNmMtYWUwMS1lNmFhMzQyMzVlNzUiLCJldmVudF9pZCI6IjBmNTk3MmM5LTI3NjgtNDlkNy04ZmFmLTJlZjYwNTQ5MDQ4YiIsInRva2VuX3VzZSI6ImFjY2VzcyIsInNjb3BlIjoiYXdzLmNvZ25pdG8uc2lnbmluLnVzZXIuYWRtaW4iLCJhdXRoX3RpbWUiOjE1OTMxMDgyMDEsImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy13ZXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtd2VzdC0yX1IwOVd3czg5cCIsImV4cCI6MTU5MzExMTgwMSwiaWF0IjoxNTkzMTA4MjAxLCJqdGkiOiI4ODVhOThhMS0zMDBmLTQ5MTItODJjZC1hOGE2OWVjNzViY2MiLCJjbGllbnRfaWQiOiI0aDA5b3FlMzY4bjBnZDM3MWxpcTk5bGU2YiIsInVzZXJuYW1lIjoiYjJhNDFmZTctNzMzZS00YzZjLWFlMDEtZTZhYTM0MjM1ZTc1In0.OURHt76-V3IDtdZ9xASXf3V8FamK-dyFibUTheR8pBCwee17TDwVc6Zszfx_CgLvhnLCBWnBKYfmuEg-vBNNAKuqF1PujrEOR6TetU0u_ic7LYuVOO6AxtOke-r9GkeNJI8BiMF0ThK9t3IvEjPToaG21tq3rKwdizXKj3-ePLDoZ18sb8N_Ea8yX-Myp3bbuRfkSJNWVSTtMMiCdAu3rMgP10w3HzCAumUtrsJqkN1ghYUjKsD1joCigIGcQ2soXLTwe8HMo3QfGysPYbCeCswjfzBqtexfR1HcXI6WD4HdlWL0ZLZvbRy7ooXKvglPeVgkMRTcCZ8FFoc-sfAzIQ'
x = container.jwt_decoder.decode(token)

pprint(x)
